server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: aws-localstack
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566